### ISSUE TITLE
Sieve recipes does not exist.

### ISSUE THREAD

**Issue by Fatcow007** [Discomanco/Enigmatica2ExpertSkyblock#101]
#### Crash Report

[pastebin/gist/etc link here]

As of most recent update(v 1.3a), sieve recipes have mostly disappeared.

Sieve is no longer accepting gravel or crushed netherrack, but recipe for crushed endstone still works.

Perhaps the recent fix to gem drops have caused this issue?

**Comment by Fatcow007** [comment]
Nevermind, it was locked down by queststage thing.

**Comment by Pertzaa** [comment]
what stage opens them i can only use dust
