### ISSUE TITLE
Shops/community goods exchange (SUGGESTION)

### ISSUE THREAD

**Issue by Caakkee** [Discomanco/Enigmatica2ExpertSkyblock#103]
I was thinking that it would be cool if people could open up their own shops and sell things. Of course there would be the issue of currency and where to put the shops. You could use the coins from Thermal Expansion as a currency with the rarest material being worth more which might be confusion for some people. Or you could add a different mod that add money or a currency. The shops could be built in the nether since everyone's nether portal leads to the same place. Or you could make an island somewhere in the over world and make a command to get there with plots for people to build their shops. to get their fair share of money you could create another command to give people a set amount of money with the only way to earn more by doing quests or opening up shops. Thanks for taking the time to look at my suggestion hope you implement it in some shape or form.

**Comment by Caakkee** [comment]
It could be implemented on all servers but i was specifically talking about expert skyblock

**Comment by NillerMedDild** [comment]
This would not make sense to add to the general modpack at all, you should implement it on your own server.
