### ISSUE TITLE
Can't acquire boron

### ISSUE THREAD

**Issue by sybaik1** [Discomanco/Enigmatica2ExpertSkyblock#106]
#### Issue Description
I can't find a way to get  boron. A closed issue about boron says that to get boron from sieving crushed netherack  but it does not show up in the JEI and it doesn't work. Is it gated? I need boron for the advanced rocketry gate and the extream reactors. Or is there any other way of getting boron?

#### Modpack version (Do not use "latest")
1.3a

#### Crash Report

[pastebin/gist/etc link here]

**Comment by DrTasslehoff** [comment]
The sieve issue is caused because the SieveRegistry.json file is malformed.  The last entry has an extra , that is causing it not to load properly:
    {
      "drop": {
        "name": "contenttweaker:sapphire",
        "meta": 0
      },
      "chance": 0.05,
      "meshLevel": 4
    },      <----- [[[ Remove this comma]]]
  ]
}

**Comment by sybaik1** [comment]
thank you. I was stuck on that part
