### ISSUE TITLE
Glitch on inventory

### ISSUE THREAD

**Issue by Waysepp** [Discomanco/Enigmatica2ExpertSkyblock#108]
#### Issue Description
Glitch on inventory (like ghost items) you can see the item on your inventory slot but the slot is actually empty at server properties.He said the problem to me. I play on the server with my friend I was the server owner. I am didn't see the problem at my own inventory. He said the problem solved for 10 minutes if he 
disconnect and reconnect at the server.
#### Modpack version (Do not use "latest")
v1.4
#### Crash Report
not a crash

**Comment by Waysepp** [comment]
sorry for bad english

**Comment by NillerMedDild** [comment]
He is doing something that is desyncing him from the server, I'm afraid we would need a lot more information to even have a chance at finding the cause.
