### ISSUE TITLE
Nuclearcraft Fission controller wrong itemID

### ISSUE THREAD

**Issue by DrTasslehoff** [Discomanco/Enigmatica2ExpertSkyblock#109]
#### Issue Description
The Fission controller quest in Nuclearcraft and the Extreme Reactors reactor controller requires itemID #5465 (nuclearcraft:fission_controller_new_idle). This does not show up anywhere in JEI and I cannot see a way to obtain it. The fission controller that can be crafted is itemID #11739 (nuclearcraft:fission_controller_new_fixed). It works fine for the multi-block but not for quest completion 
or the crafting

#### Modpack version (Do not use "latest")
v1.4

**Comment by CaveJohnsonn** [comment]
Same issue here, any fixes yet?
![2018-08-30_03 19 58](https://user-images.githubusercontent.com/41660739/44867456-7a5a5600-ac4d-11e8-8120-a4f1b62aad30.png)
![2018-08-30_03 26 17](https://user-images.githubusercontent.com/41660739/44867463-7deddd00-ac4d-11e8-8400-66205743761e.png)

**Comment by GuntherDW** [comment]
Looks like the the ItemID's changed between 1.3a and 1.4. I originally crafted the block and used it did trigger the quest correctly in 1.3a, but the one I just crafted in 1.4 does indeed not work as intended.

**Comment by CaveJohnsonn** [comment]
2 weeks later, is this bug being reviewed?

**Comment by JonnaJudin** [comment]
Here is a fix for the issue described:
https://github.com/JonnaJudin/Enigmatica2ExpertSkyblock/commit/ec780d8ae1f3684b66463d4a89a32ab9b3ccdbc0#diff-93d5612646ad25dbdc9e82d82dc4393a

I tested the fix quickly in creative mode manually crafting each affected item and verified that I was able to finish the quests
