### ISSUE TITLE
Quest for Mystical Agriculture gate not completing

### ISSUE THREAD

**Issue by loadstones** [Discomanco/Enigmatica2ExpertSkyblock#112]
both items say complete but it wont let you claim the reward and finish the quest. Strangely the description for the master infusion stone is red.

**Comment by forkinme** [comment]
I was able to complete this with just the lesser infusion stone (I won it from a loot box) but I had to toggle back and forth between the two stones trying to complete it before it completed. I don't recall exactly what sort of fiddling I did there to get it to complete.

**Comment by NillerMedDild** [comment]
Sure thing, I had configured it wrong :)

**Comment by NillerMedDild** [comment]
Oh and thank you for reporting it.
