### ISSUE TITLE
IE Block of Steel missing from JEI

### ISSUE THREAD

**Issue by forkinme** [Discomanco/Enigmatica2ExpertSkyblock#113]
**EDIT**:

The IE Block of Steel is referenced by the Advanced Thermionic Fabricator recipe but is missing from JEI. IE's Block of Steel can be made from TF's Block of Steel via Chisel but there's no obvious way to discover this. I'm unsure if it being this hidden is intentional.

**ORIGINAL ISSUE FOLLOWS:**

#### Issue Description

The Advanced Thermionic Fabricator cannot be built. The recipe references corner blocks made of Immersive Engineering steel blocks (in both the recipe config json and the preview in-game) but that block cannot be created because steel blocks were unified to the Thermal Foundation steel block.

From the machine json:
```
        {
            "x": -2,
            "y": -1,
            "z": 0,
            "elements": [
                "immersiveengineering:storage@8"
            ]
        },
```

I built the machine in-game per the guide using the only "Block of Steel" in JEI but the machine structure wasn't detected. I cheated in IE steel with `/give player immersiveengineering:storage 8 8` and replaced just the steel block corners, the machine structure was then detected.

#### Modpack version
1.4

**Comment by DrTasslehoff** [comment]
You can chisel them into the IE steel blocks

**Comment by forkinme** [comment]
Nice catch! I didn't think of that. It's pretty non-obvious since you can't find it in reverse (looking for the IE block) via JEI, but you can find it looking forward (looking for things you can do with the Thermal Foundation block it's in the chisel tab). I'm going to rewrite the issue so the mod owner can act on it or close it since I don't know if the obscurity was intentional.

**Comment by NillerMedDild** [comment]
Add explicitly with JEI CraftTweaker: `mods.jei.JEI.addItem(<immersiveengineering:storage:8>);

Thank you for an excellent report :)
