### ISSUE TITLE
Advanced Rocketry Twilight "planet" broken

### ISSUE THREAD

**Issue by GuntherDW** [Discomanco/Enigmatica2ExpertSkyblock#116]
#### Issue Description
In the non-skyblock version of the pack, the mod "Twilight Forest" is included, which is set to DIM 7.
However, in this version of the pack the mod is not included which makes the Twilight forest planet bug out.
When you warp to the planet (Proxima Centauri -> Twilight) and attempt to lift off to travel to the planet it just stays in place and the rocket is unable to be used until what I assume is either a timeout or a server reboot.

The rocket just stays in place and shoots out particles once in a while giving the illusion that it is still "moving" yet it uses up no fuel but is unable to be used until said timeout.

By checking the configs I figured out that it was pointing to the actual Twilight Forest DIM ID, which was the reason it was acting up.

The solution would be to either remove said planet from the config (but saves keep their AdvRocketry planet and astroid configs IE manual copying of said configs is necessary), create a separate planet or include the mod in question.

EDIT: While not a issue that will crash the pack, just copying over the planetDefs.xml from the non-skyblock version without any modification will cause random issues. Like for example Biomes O Plenty isn't installed so worlds will just get random other biomes. Venus for example gets different warm and hot biomes instead of the single BOP biome specified in the config.

#### Modpack version (Do not use "latest")
1.4

**Comment by NillerMedDild** [comment]
Most planets now generate somewhat randomly based on pressure and temperature.
