### ISSUE TITLE
Game crashing 

### ISSUE THREAD

**Issue by UmbraFlux** [Discomanco/Enigmatica2ExpertSkyblock#117]
#### Issue Description
Every time I try to craft mekanism advanced solar generator the game crashes
#### Modpack version (Do not use "latest")
1.4
#### Crash Report
https://pastebin.com/GpgT2XLZ

**Comment by NillerMedDild** [comment]
It should work in a vanilla crafting table.

I recommend you update your java, and set Twitch to use the new version :)
