### ISSUE TITLE
UU Matter Value, issue or intentional?

### ISSUE THREAD

**Issue by Godelboard** [Discomanco/Enigmatica2ExpertSkyblock#118]
#### Issue Description
I believe there may be an incorrect setting in the replicator custom recipes. It looks like the replicator uses 1/100th of what is set in the config, and not entirely sure this was intentional.

First I did 2 stacks of litherite crystals @ 60mB uu-matter each, which seemed reasonable. Then I scanned thermal expansion machine frames and its 40mB uu-matter each?? I would just like to check that this is intended.

#### Modpack version: 1.4

![image](https://user-images.githubusercontent.com/6662420/45333271-293e4200-b52a-11e8-9586-91fd3012d865.png)

**Comment by NillerMedDild** [comment]
Intended behaviour, thank you for checking in, that's always nice :D

**Comment by Godelboard** [comment]
Ok sweet! I thought it might have been accidentally too..."generous."
If this is intended, now I can use it guilt free. Thanks and loving the pack by the way!

**Comment by NillerMedDild** [comment]
Glad to hear it :D
