### ISSUE TITLE
tinkers matock crashed the server

### ISSUE THREAD

**Issue by misshaptat** [Discomanco/Enigmatica2ExpertSkyblock#121]
#### Issue Description
so was using a cobalt heads and copper tool rod matoch from tinkers and tried to vein mine a menril tree and crashed the server at 9/12 at 8:19 est.
Mod Pack Ver. 1.4 release

No crash report, Only chat bot says Server Crash Detected

**Comment by NillerMedDild** [comment]
Moved to https://github.com/NillerMedDild/Enigmatica2Expert/issues/255
