### ISSUE TITLE
Wildberries/Ironberries Unobtainable

### ISSUE THREAD

**Issue by ImCoolYeah105** [Discomanco/Enigmatica2ExpertSkyblock#122]
#### Issue Description
Wildberries & Ironberries from Rustic are currently unobtainable. Normally these would generate in the Overworld, but do not in Skyblock. They do not generate on other planets. These are required to craft the Ultimate Stew, meaning without them a good chunk of the late game cannot be accessed.

#### Modpack version (Do not use "latest")
1.4

**Comment by NillerMedDild** [comment]
Thank you for the report.
