### ISSUE TITLE
Creative Flux Capacitor recipe broken

### ISSUE THREAD

**Issue by swoolcock** [Discomanco/Enigmatica2ExpertSkyblock#123]
The resultant item has 0 RF, so it doesn't charge any items and it doesn't trigger the bragging rights quest.  Manually giving the item through JEI will work.  Note that it will still charge and drain the Induction Matrix, it just won't charge items in the inventory.

Tested in single player survival and creative mode, both manually and using Extended Crafting's Automation Interface.

Version 1.4, no added mods.  Note that the world was migrated from 1.2.

<img width="395" alt="screen shot 2018-09-15 at 12 11 21 am" src="https://user-images.githubusercontent.com/2331297/45557120-10ac8f80-b87c-11e8-953f-15d1a51398d3.png">

**Comment by NillerMedDild** [comment]
Thank you for the report.
