### ISSUE TITLE
Excavator doesn't works

### ISSUE THREAD

**Issue by syrun97** [Discomanco/Enigmatica2ExpertSkyblock#124]
#### Issue Description
Excavator can't get aluminium and rutile ores from bauxite vein.
Is excavator disabled?
#### Modpack version (Do not use "latest")
1.4 ("latest" in twitch)
#### Crash Report
![2018-09-17_16 56 37](https://user-images.githubusercontent.com/19798397/45611708-51362400-ba9b-11e8-96d0-e7b681f55a78.png)
![2018-09-17_16 56 42](https://user-images.githubusercontent.com/19798397/45611709-51ceba80-ba9b-11e8-97a9-842c45694c46.png)
![2018-09-17_16 56 46](https://user-images.githubusercontent.com/19798397/45611710-51ceba80-ba9b-11e8-81a6-3d271c211768.png)
![2018-09-17_16 56 50](https://user-images.githubusercontent.com/19798397/45611711-51ceba80-ba9b-11e8-9662-b41f3b23b148.png)

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
I apologize for the stupid question, but is the Excavator in the same chunk as you got the Mineral Sample from?

**Comment by NillerMedDild** [comment]
Confirmed.

**Comment by NillerMedDild** [comment]
A user on the Enigmatica discord has informed me that putting a large amount of dirt underneath the wheel of the Excavator fixes this issue.

**Comment by GuntherDW** [comment]
Correct, the excavator actually needs a couple blocks under the "wheels" to actually mine anything.
