### ISSUE TITLE
Auto Compressor Doesn't Work

### ISSUE THREAD

**Issue by cwilkinsvi** [Discomanco/Enigmatica2ExpertSkyblock#125]
#### Issue Description
All Ex nihilo ore pieces can not be crafted in the ex compressum auto compressor. Changed since last version. Only recipes for ore pieces are now crafting tables.
#### Modpack version (Do not use "latest")
1.5
#### Crash Report
N/A
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
So the issue isn't that recipes for Ore Pieces -> Ore are gone, but that the Auto Compressor can no longer compress them, right?

**Comment by cwilkinsvi** [comment]
Correct. Further testing last night showed the auto compressor had no uses.

**Comment by NillerMedDild** [comment]
Very misleading title :P

**Comment by cwilkinsvi** [comment]
It was somehow still compressing redstone yesterday when I first loaded up the pack, so I thought it was an issue with Ex Nihilo. My apologies.

**Comment by NillerMedDild** [comment]
No worries :)

**Comment by NillerMedDild** [comment]
I'm fairly certain the issue is that resources obtained through Sieves have empty NBT data.

**Comment by NillerMedDild** [comment]
Fixed in https://github.com/BloodWorkXGaming/ExNihiloCreatio/issues/115#issuecomment-422751064
