### ISSUE TITLE
Unable to make nor view the recipe for Starlight Crafting Altar and above.

### ISSUE THREAD

**Issue by LYoshiiro** [Discomanco/Enigmatica2ExpertSkyblock#127]
Not sure if im the only one but i tested trying to make the Starlight Crafting Alter in my survival and test worlds and neither work, could not get the receipe to work, not sure if theres a additional gate or something but jei doesnt show it too.

Version : 1.5

**Comment by NillerMedDild** [comment]
You need to progress through Astral Sorcery in order to view and craft it.
