### ISSUE TITLE
Plant gatherer from Industrial Forgoing duping Mystical Agriculture seeds.

### ISSUE THREAD

**Issue by discotyme** [Discomanco/Enigmatica2ExpertSkyblock#128]
Issue Description: Just as the title states, The plant gatherer dupes the seeds from mystical agriculture which can be abused very easily sort of taking away the whole "Expert" appeal of the pack, if this was fixed in the latest version of the mod pack feel free to close the report.

Modpack version: 1.4

**Comment by NillerMedDild** [comment]
This does not happen in 1.5, thank you for the report anyhow :)
