### ISSUE TITLE
Morph-o-Tool not working with botania wand of the forest and ae2 network tool

### ISSUE THREAD

**Issue by Fatcow007** [Discomanco/Enigmatica2ExpertSkyblock#131]
#### Issue Description

Morph-o-Tool is not working with botania wand and ae2 network tool.
The config file seems incorrect.

In morphtool.cfg

        botania:twigWand
        appliedenergistics2:ToolNetworkTool

change to->

        botania:twigwand
        appliedenergistics2:network_tool

Maybe updating the pack caused it, as most recent version of Morph-o-Tool v1.2-16 (which is the version this pack uses) already addressed and fixed this issue. Configs might not have updated accordingly.

#### Modpack version (Do not use "latest")
Version 1.6

#### Crash Report

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Thank you for the report, and the fix, much appreciated :D
