### ISSUE TITLE
Unnecessary mod taken over from the overworld version?

### ISSUE THREAD

**Issue by GuntherDW** [Discomanco/Enigmatica2ExpertSkyblock#135]
#### Issue Description
In the overworld version of the pack the mod "Broken Wings" is included. It is setup to not allow you to fly in the Twilight Forest.
In the skyblock version of the pack however, due to Twilight Forest not being included it is a bit unnecessary.

In an RFTools Dimension I wasn't able to use my flight ability so at first I looked at RFTools Dimension to see if it was an effect but when I noticed nothing of the sort in the code, and noticed that the DimID for that specific Dim was 7 some dots were starting to connect.

While this might be useful in the overworld version of the pack, in the skyblock version it just seems rather useless being that Twilight Forest isn't included in the pack, making people confused about what is stopping them from flying in a random RFTools Dimension they made.

#### Modpack version (Do not use "latest")
1.6

**Comment by NillerMedDild** [comment]
Thank you for correcting yet another annoying left over :D
