### ISSUE TITLE
Duplicate Quest (Extra Utilities Machine Block)

### ISSUE THREAD

**Issue by Ludi87** [Discomanco/Enigmatica2ExpertSkyblock#14]
#### Description
Machine Block is used in 2 Quests.
1: Gate for Extra Utilities
2: Machine Block Quest in Extra Utilities section.

Maybe remove the one in extra utilities? Its automatically done because I already crafted the Machine Frame for the Gate.

#### Modpack version
0.1

**Comment by BluePanda13** [comment]
The gats ID is #36
and the XU one is #330
Just to make it easier:)

**Comment by NillerMedDild** [comment]
The second quest is just there to indicate it's in the recipe for all child quests.
