### ISSUE TITLE
Steel Rod recipe?

### ISSUE THREAD

**Issue by Ludi87** [Discomanco/Enigmatica2ExpertSkyblock#15]
#### Issue Description
Wondering if this is the only supposed earlygame Steel Rod recipe... (besides the plate presser). Looks a bit confusing to me :D

(Trying to make steel scaffolding for the metal press.)

#### Modpack version (Do not use "latest")
0.1

![steel rod](https://user-images.githubusercontent.com/13112051/41511574-b8671946-7279-11e8-977e-131ea51fb4d8.png)

**Comment by NillerMedDild** [comment]
What's wrong with it?

**Comment by Discomanco** [comment]
Craftable in the Small Plate Presser
