### ISSUE TITLE
Configure Armoreable Mobs

### ISSUE THREAD

**Issue by BluePanda13** [Discomanco/Enigmatica2ExpertSkyblock#17]
alot of mobs spawned with nano suits and manaweave armor and its kinda hard to kill them with a wooden sword.
p.s. i got their armor after i killed them.. and i dont think we hould get that armor at the start.

**Comment by NillerMedDild** [comment]
I was thinking this could be tied to GameStages - Opening a gate would also result in upgrading the possible armors of mobs.

**Comment by NillerMedDild** [comment]
Just curious, what did you end up doing?

**Comment by Discomanco** [comment]
Reduced the chance of armoured mobs to spawn by 90%
