### ISSUE TITLE
Easier iron gear recipe

### ISSUE THREAD

**Issue by BluePanda13** [Discomanco/Enigmatica2ExpertSkyblock#18]
To make an iron gear i need the metal press.
For the metal press I need a block of redstone for each steel rod that i make for the steel scaffloding.
Even more redstone for the pistons and the redstone engeeniring block.
To make the redstone i need at least the iron casing for the combustion because the stone one doesnt have enough HU.
The Iron casing recipe require me to make an iron gear which i cant unless i get red orchid which is a grind..

**Comment by BluePanda13** [comment]
And to make the metal press i need to make first the coke oven and the blast furnace
and iron should be before both of those

**Comment by Ludi87** [comment]
you can make the steel rods with the small plate presser

**Comment by Discomanco** [comment]
The way I did it, is to make a Gear Cast with Gold/Aluminum Brass on a Wooden Gear, and go from there.
Will look into a Clay Gear Cast, to see if possible.

**Comment by BluePanda13** [comment]
ok thanks

**Comment by BluePanda13** [comment]
for Gold u need glowstone which is 1300 HU in the combustion
so still iron casing or nether brick
and netherack is 900 HU

so the only way is copper and aluminum

**Comment by BluePanda13** [comment]
@Ludi87 its made by steel plates... i think iron stuff should be before making coke oven and blast furnace
