### ISSUE TITLE
Add Bonsai Trees

### ISSUE THREAD

**Issue by BluePanda13** [Discomanco/Enigmatica2ExpertSkyblock#20]
pls

**Comment by liketechnik** [comment]
Just wanted to ask for the inclusion of Bonsai Trees and found this issue. I would really find it cool if bonsai trees were added, because - especially for skyblock - it adds an earlygame alternative to the tedious and boring wood farming. So, what's going on about it?

**Comment by NillerMedDild** [comment]
I would much rather people automate tree farms in other ways, I find the Bonsai Trees too simple.
