### ISSUE TITLE
Make Ex Nihilo Available Early Game

### ISSUE THREAD

**Issue by NillerMedDild** [Discomanco/Enigmatica2ExpertSkyblock#26]
I'd personally prefer if both Ex Nihilo and Sky Resources were available to begin with, so players can pick whichever they feel like. For some reason I feel like the crafting mechanics would fit in better in the midgame.

**Comment by Discomanco** [comment]
I fear one is going to overshadow the other, in terms of efficiency and speed

**Comment by BluePanda13** [comment]
most will use EX nihilo and not sky resources i think

**Comment by NillerMedDild** [comment]
I think most would start with Ex Nihilo, and maybe branch into Sky Resources for bulk items. 
But is that a bad thing?

**Comment by NillerMedDild** [comment]
I'm gonna take this as a no :)
