### ISSUE TITLE
Duplicate Quest (Botania Petal Apothecary)

### ISSUE THREAD

**Issue by BluePanda13** [Discomanco/Enigmatica2ExpertSkyblock#32]
Description
Petal Apothecary is used in 2 Quests.
1: Gate for Botania
2: Petal Apothecary Quest in Botania section.

Maybe remove the one in Botania? Its automatically done because I already crafted the Petal apothecary for the Gate.

Modpack version
0.2

**Comment by NillerMedDild** [comment]
The second quest is just there to indicate it's in the recipe for all child quests.

**Comment by BluePanda13** [comment]
its not the same as the XU machine frame?

**Comment by NillerMedDild** [comment]
What?

**Comment by BluePanda13** [comment]
the quest of the machine frame from XU was duped too and he added it to 1.0

**Comment by Discomanco** [comment]
Doesn't really matter that there's duplicate quests, when the 2nd quest doesn't have any (relevant) rewards
