### ISSUE TITLE
Remove ftbutils

### ISSUE THREAD

**Issue by bennyb1971** [Discomanco/Enigmatica2ExpertSkyblock#41]
Just because it causes several issues serverside.

**Comment by NillerMedDild** [comment]
I second this, Sky Resources handles teleportation, and backups aren't our responsibility.

**Comment by kristu** [comment]
without ftbutils how will easy enable chunkloading for singleplayers users...?
 if the problem is just with servers why not the servers remove then...?

**Comment by BluePanda13** [comment]
cuz then all the players wont be able to play...
and there is IC2 chunkloader

**Comment by NillerMedDild** [comment]
You can add it yourself for SP :)

**Comment by BluePanda13** [comment]
that too

**Comment by Kbotei** [comment]
What were the issues with that ftbutils causes with servers? I was using it to prevent creepers from blowing up my mob farm. I also tend to gravitate towards packs that have backup mods included.

**Comment by NillerMedDild** [comment]
It caused random crashes on SpongeForge, and it's a hassle to configure, as it's config files have a tendency to move, be renamed, regenerate or otherwise be invalidated.
