### ISSUE TITLE
logWood for gear makes wood pile not 2 wood gears

### ISSUE THREAD

**Issue by Matchyman** [Discomanco/Enigmatica2ExpertSkyblock#44]
#### Issue Description
Recipe for wooden gear, using logs gives forestry wood pile instead of 2 wood gears :)
Which one of you dungoofed this time :P
#### Modpack version (Do not use "latest")
v1.0
#### Crash Report

[pastebin/gist/etc link here]

**Comment by Matchyman** [comment]
Wooden gear from tesla core lib

**Comment by Discomanco** [comment]
Well, neither, just conflicting recipes :P But, #42
