### ISSUE TITLE
Flint in combustion chamber produces blaze powder instead of gunpowder

### ISSUE THREAD

**Issue by Kbotei** [Discomanco/Enigmatica2ExpertSkyblock#48]
#### Issue Description
When placing flint in a combustion chamber blaze powder is produced when JEI shows gunpowder as the result. Tested with a stone combustion heater and iron casing.

Edit: I also just found that if you put 3 flint in a fully heated stone heater with netherrack casing it turns into gunpowder correctly.

#### Modpack version 
1.0

**Comment by predakanga** [comment]
Upstream bug: https://github.com/Bartz24/SkyResources/issues/140

As a workaround, it shouldn't affect the combustion collector (though that won't work with the stone combustion heater).

Can also be avoided by downgrading Sky Resources to 2.3.0 and Sky Compression to 1.2.2.1

**Comment by Kbotei** [comment]
That makes sense. I noticed that the combustion chamber seemed to be exploding twice.

**Comment by erplsf** [comment]
It is not a bug, I think it's a feature - when you use Combustion Collector you properly get Blaze Powder.

**Comment by Discomanco** [comment]
Doing 2 crafts with 1 button press sounds like a bug.
IE Flint -> Gunpowder -> Blaze Powder

**Comment by Kbotei** [comment]
I should have probably mentioned this, but I am not using a combustion collector. My setup was as mentioned above with cobble stone on all sides.
