### ISSUE TITLE
Early game Endstone Casing

### ISSUE THREAD

**Issue by davqvist** [Discomanco/Enigmatica2ExpertSkyblock#49]
#### Issue Description
I got from a Loot Bag Purpur Blocks. Now with Glowstone I was able to make Endstone and therefore Endstone Casings already 8h in the pack. This seems like a progression break. I recommend either disabling the Ex Nihilo Endstone recipe or remove Purpur Blocks from the Loot Bag.

#### Modpack version (Do not use "latest")
1.0

**Comment by Discomanco** [comment]
Loot Boxes can give great rewards, that can make you skip certain steps.
Sure it breaks the progression of Sky Resources itself a bit, but not the modpack as a whole
