### ISSUE TITLE
Missing boron alchemical ore dust recipe in JEI

### ISSUE THREAD

**Issue by Kbotei** [Discomanco/Enigmatica2ExpertSkyblock#56]
#### Issue Description
Missing Boron alchemical ore dust recipe in JEI. The boron ingot has the alchemical dust listed in the condenser tab, but clicking on the dust does not bring up the recipe for the dust.
#### Modpack version
1.0

**Comment by BluePanda13** [comment]
its not missing 
its disabled u get boron by sieving crushed netherrack in regular sieve
or by siveing compressed nether gravel in heavy sieve

**Comment by Kbotei** [comment]
I did see that it could be obtained via sieving, but because the condenser tab was shown for the ingot I assumed it was still a valid way of obtaining the ore. If possible I would recommend hiding the condenser tab from the ingot in JEI.

**Comment by BluePanda13** [comment]
its because of the mod
alot of dusts are in JEI but they are diabled

**Comment by Discomanco** [comment]
A lot of dusts are indeed disabled, but I forgot to remove the recipes from the Condenser
