### ISSUE TITLE
Titanium recipe is missing (put niller's hotfix in the next version)

### ISSUE THREAD

**Issue by BluePanda13** [Discomanco/Enigmatica2ExpertSkyblock#61]
its because the machine's bluepring is missing

**Comment by NillerMedDild** [comment]
[modularmachinery.zip](https://github.com/Discomanco/Enigmatica2ExpertSkyblock/files/2174060/modularmachinery.zip)
Place in `config` folder

**Comment by BluePanda13** [comment]
@NillerMedDild  is it the right one this time?

**Comment by NillerMedDild** [comment]
Tip.
