### ISSUE TITLE
Item/Recipes Not Showing Up Properly In JEI

### ISSUE THREAD

**Issue by Numorphan** [Discomanco/Enigmatica2ExpertSkyblock#62]
#### Issue Description

The Universal Fluid Cell from IC2 isn't in JEI if you search for it, but you can find the recipe from searching for the Compressor's recipes, and clicking it from there. This is important as the IC2 Blast Furnace requires Universal Fluid Cells filled with air from the Compressor (which isn't mentioned in the Blast Furnace quest either, so people would be very confused when it doesn't start working on the iron).

This isn't as important, but some recipes are not showing up properly. The recipe for IC2 carbon fibre says it takes 4 pulverized coal and nothing else, but IC2 coal dust (produced from the Thermal Centrifuge as well as macerating a Coal Block) works as well (admittedly, the recipe says it takes any coal dust, but it doesn't cycle through the possibilities like normal. No idea if you can do anything about that though). Not too bad, but I was surprised when the Coal Block Macerator recipe returned something other than what the recipe said it would, and that the different thing still worked even though it didn't cycle through in the carbon fibre recipe.

#### Modpack version (Do not use "latest")

v1.1

**Comment by NillerMedDild** [comment]
This is all intended behaviour.
* Cycling through ingredients is more confusing than anything imo.
* Various modded Fluid Cells take up about 15 JEI pages combined, which is why they're hidden.
Thank you for the report :)

**Comment by Numorphan** [comment]
Fair enough, but some indication should be given about the existence (and requirement) of the Universal Fluid Cells as pertains to steel making. Probably in the corresponding quest.

**Comment by NillerMedDild** [comment]
Good point, we'll get that fixed.
