### ISSUE TITLE
Viewing recipes in JEI crashing game

### ISSUE THREAD

**Issue by briony805** [Discomanco/Enigmatica2ExpertSkyblock#63]
Hey.

I'm so early in the game. I'm trying to craft a vanilla chest, and I obviously noticed the default recipe was changed. So obviously I looked up the recipe in JEI but the game keeps crashing when I left click on the chest.

I have tried upping the ram from 4GB to 6GB to 8GB (out of 16GB).

Also java arguments are as follows:
-Xmx8192m 
-Xms256m 
-XX:PermSize=256m 
-Dminecraft.applet.TargetDirectory="C:\Users\BCT\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert Skyblock" 
-Dfml.ignorePatchDiscrepancies=true 
-Dfml.ignoreInvalidMinecraftCertificates=true 
-Duser.language=en 
-Duser.country=US

Modpack version 1.0

Latest crash log is here:
https://pastebin.com/rpc4rBHK

Any help would be greatly appreciated, I was really looking forward to playing this pack. Thanks.

**Comment by NillerMedDild** [comment]
The latest version of the modpack is 1.1, can you replicate this in that version?

**Comment by BluePanda13** [comment]
still crashing ppl in 1.2 when trying to check what can we make with cobble
(right clicking on cobble in JEI)

**Comment by NillerMedDild** [comment]
mezz/JustEnoughItems#1296

**Comment by BluePanda13** [comment]
so is it the new version of JEI?

**Comment by mezz** [comment]
This crash is different from the linked JEI issue, it is a crash from CTM.
Thankfully it is already reported and fixed in the latest version: https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63

**Comment by alpal01** [comment]
it should be fixed now that CTM updated

**Comment by NillerMedDild** [comment]
Is this still occuring @briony805?
