### ISSUE TITLE
Rock crystal won't craft in combustion multiblock

### ISSUE THREAD

**Issue by steeloway** [Discomanco/Enigmatica2ExpertSkyblock#66]
#### Issue Description
I put 4 stardust, 1 diamond, 4 aquamarine in a combustion multiblock with netherbrick casing and an iron heater with maximum heat and pressed button. An explosion occured and my items and heat were taken away but no crystal was formed 

#### Modpack version (Do not use "latest")
Version 1.1

**Comment by BluePanda13** [comment]
use combustion collector and it will fix it
