### ISSUE TITLE
Add Sky Compression

### ISSUE THREAD

**Issue by NillerMedDild** [Discomanco/Enigmatica2ExpertSkyblock#7]
Could be nice, water gathering is sloooow

**Comment by Ludi87** [comment]
I believe thats the Sky Compression mod. I think it also adds machines that auto-process compressed materials instead of smoothstone/...

**Comment by Discomanco** [comment]
Remove (already done by XU2):
 - Compressed Cobblestone
 - Compressed Gravel
 - Compressed Netherrack
 - Compressed End Stone
 - Compressed Dirt
 - Compressed Sand
