### ISSUE TITLE
Crash on second load of world

### ISSUE THREAD

**Issue by forkinme** [Discomanco/Enigmatica2ExpertSkyblock#78]
#### Issue Description
Attempting to load a world a second time (load world, quit world, load world again) results in Minecraft hanging perpetually. Log points at Immersive Engineering, this has been fixed in release 0.12-84 https://github.com/BluSunrize/ImmersiveEngineering/issues/3094

#### Modpack version (Do not use "latest")
1.2a (Immersive Engineering 0.12-83)

**Comment by Discomanco** [comment]
Always attach a crashlog, even if it has been resolved by the mod author :)

**Comment by forkinme** [comment]
Whoops, my bad. MC log: https://paste.ee/p/3GQM4#s=0&l=10262

Do you want to re-open the issue since it's still a problem with the modpack even though the mod author has fixed it on their end?
