### ISSUE TITLE
Game crashes when looking at recipies that use cobblestone_stairs.

### ISSUE THREAD

**Issue by MrT3chnik** [Discomanco/Enigmatica2ExpertSkyblock#81]
#### Issue Description
When you use JEI to search for recipies that use cobblestone_stairs (press "U" over the item, or rightclick on a stair in JEI)
#### Modpack version (Do not use "latest")
1.2a
#### Crash Report
The game crashed whilst updating screen events
Error: java.lang.RuntimeException: Fluid tinker_io.fluids.PureMetal@7198821e (puremetal, class tinker_io.fluids.PureMetal) from item 1xic2.fluid_cell@0 returned an unregistered block from getBlock(). This is a major bug in the mod that fluid belongs to.

-Update:
It crashes with most of the cobblestone items, not only stairs.

**Comment by JonnaJudin** [comment]
Lots of other items trigger this bug too, it can be prevented by changing the painter setting in enderIO.cfg to false. 
B:allowTileEntitiesAsPaintSource=false

It will stop from using tileEntities from being used, but in my opinion the tradeoff compared to crashes would be better.

 painter {
        # When enabled blocks with tile entities (e.g. machines) can be used as paint targets. (synced from server) [default: true]
        B:allowTileEntitiesAsPaintSource=false
