### ISSUE TITLE
Thaumcraft not accessable

### ISSUE THREAD

**Issue by Rene98** [Discomanco/Enigmatica2ExpertSkyblock#89]
Issue Description
When I Right click a bookshelf with the salis mundus nothing happens, although I should get the thaumonomicon.
#### Modpack version (Do not use "latest")
1.2a
#### Crash Report
there is no crash report or any signs in the logs that could help with this
[pastebin/gist/etc link here]

**Comment by BluePanda13** [comment]
make vis crystal
throw on the ground
pick it up
go to sleep
and then make the thaumonomicon.
@Rene98

**Comment by Rene98** [comment]
Thanks!
