### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by UmbraFlux** [Discomanco/Enigmatica2ExpertSkyblock#98]
#### Crash Report
https://pastebin.com/h9TnLAib

**Comment by Listerman69** [comment]
Hi,

Same here.
Yesterday playing happenly today cant start the pack.

Modpack Version:1.3a

 Crash Report.
https://pastebin.com/Hb5fg5k9

**Comment by forkinme** [comment]
It's not just you or the modpack, it's many modded players. Mojang pushed an update that had a bad interaction with Forge and some mods. Forge has released an update to address the issue, the modpack needs to update https://github.com/MinecraftForge/MinecraftForge/pull/5105.

In the meantime, workarounds are available depending on what launcher you're using: https://www.reddit.com/r/feedthebeast/comments/97tejb/psa_gendustry_and_extrautils2_are_down_right_now/

**Comment by forkinme** [comment]
For Modpack 1.3a upgrading Forge to 1.12.2-14.23.4.2751 resolved this for me. This might cause issues for those on an older version of the modpack due to older mods having issues with newer forge, so YMMV

**Comment by UmbraFlux** [comment]
Worked like a charm, Thanks 👍

**Comment by Listerman69** [comment]
Worked also for me thx
